server:
  port: ${SERVER_PORT:32100}

logging:
  level:
    root: INFO
    org.hananaharonof: DEBUG

spring:
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.hananaharonof.payment.kafka.serializer.JavaSerializer