server:
  port: ${SERVER_PORT:32101}

logging:
  level:
    root: INFO
    org.hananaharonof: DEBUG

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/payment
    username: root
    password: mysql123
  jpa:
    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: create